### PR TITLE
Add encryption support for OOXML

### PR DESCRIPTION
**Pull request by stephane-rouleau**
This is a port of the C++ library https://github.com/herumi/msoffice to add native Python support for encryption. 

OLE file writing had to be ported over as olefile does not do the heavy lifting at this stage.

I have a few more tests I'd like to run, especially with larger files, but I wanted to get your feedback on this initial stab at it.

### CODE REVIEW

**Comment by nolze** [comment]
So amazing! This is monumental work.
Basically everything seems fine, but let me take some time to review it.
I hope to merge this with minimal changes, and do more careful preparation for a new release afterwards.

**Comment by nolze** [comment]
I made and commited some small edits, including:

- Update LICENSE.txt to include the text for herumi/msoffice (BSD-3)
- Run formatter (black)
- Change some function names to the snake case from the camel case
- Edit comments
- Edit README

Diff: https://github.com/stephane-rouleau/msoffcrypto-tool/compare/03ea21f...5cd2ee1?diff=split&w=

Any feedback would be appreciated. I will merge this if there seems no problem.

**Comment by stephane-rouleau** [comment]
It looks good to me, thank you for the cleanup!

**Comment by nolze** [comment]
Merged, thanks a lot!

**Pull request merged**
