### PR TITLE
add "verify_passwd" and "verify_integrity" option

### PR DESCRIPTION
**Pull request by jeffli678**
#45

### CODE REVIEW

**Comment by nolze** [comment]
Thanks! Overall it looks good to me. I'll take time to review and suggest some minor changes within 1-2 weeks.
To put your name in the [contributors page](https://github.com/nolze/msoffcrypto-tool/graphs/contributors), please make sure that your commits are associated with your GitHub account.

**Comment by nolze** [comment]
Sorry for taking time to look into this; please wait a little while.

**Comment by jeffli678** [comment]
> 
> 
> Sorry for taking time to look into this; please wait a little while.

Never mind, please take your time!

**Comment by nolze** [comment]
Finally I'm happy to get ready to merge your PR.

I added some changes, especially to `ecma376_agile.py`. Please let me know if you find any problem. Some notes:

- Did some rename
- To keep crypto methods stateless, I decided not to share the result of hashing iteration in Agile between makekey_from_password and verify_password, but do once for each (this could be improved in future)
- verify_password and verify_integrity is False by default for now, but could be True by default in 5.x. (with optimization)
- Add some tests and looks fine

**Comment by jeffli678** [comment]
Your changes look nice to me. I will also check my email and let you know.

**Comment by jeffli678** [comment]
I updated my email to the correct one. If you do not have other issues, please accept the PR. 

To keep track of what I did: 

1. pull the remote to my local and resolve the merge conflicts. This brings you changes to my local. 
2. rebase -i, and then amend the email in my two commits.
3. force push

I hope that I did it correctly. Interestingly GitHub updates the PR automatically so I do not need to file a new one.

**Comment by nolze** [comment]
Looks good to me. Thank you for your patience and cooperation!

**Pull request merged**
